# Resolver to choose a 'specific' stackage snapshot or a compiler version.
# resolver: lts-14.27
# resolver: lts-15.3
# resolver: lts-15.16
# resolver: lts-16.3
resolver: lts-16.3
# resolver: nightly-2020-06-29.

# User packages to be built.
packages:
  - .
